title: Cobb
theme: null
markdown: kramdown
kramdown:
  input: GFM
destination: ./_site
exclude: ['_working', '_docs']
collections:
   articles:
      name: Articles
      layout: default
      output: true
      permalink: /:collection/:path
      show_github_history: true
      prepend_css_files:
       - article.css
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
sass:
    sass_dir: _sass